baseurl: "http://team2059.org/"
languageCode: "en-us"
title: "The Hitchhikers"
metaDataFormat: "yaml"
paginate: 8
taxonomies:
    blog: "blog" # Used to create categories by year grouped as "/blog/YYYY".
    resources: "resources" # Used to create categories such as "resources/code/*"
menu:
    main: # The menu at the top of the page.
      - Name: "Home"
        Identifier: "home"
        URL: "/"
        Weight: 1
      - Name: "About"
        Identifier: "about"
        URL: "/about/"
        Weight: 2
      - Name: "Blog"
        Identifier: "blog"
        URL: "/blog/"
        Weight: 3
      - Name: "Resources"
        Identifier: "resources"
        URL: "/resources/"
        Weight: 4
      - Name: "Contact"
        Identifier: "contact"
        URL: "/contact/"
        Weight: 5
blackfriday:
    plainIdAnchors: true
